### ISSUE TITLE
Support Rethink changefeed watching

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-profiler#6]
With Rethink you need to turn off changefeed watching for now (`watch: false` in the options) as changes run the after hooks without first running the before ones.

```text
Promise  Promise {
  <rejected> { TypeError: Cannot read property 'hrtime' of undefined
    at Object.timeEnd (node_modules\feathers-profiler\lib\index.js:150:38)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  hook: 
   { data: [Object],
     params: [Object],
     callback: undefined,
     method: 'create',
     type: 'after',
     app: [Object],
     service: [Object],
     result: [Object],
     path: 'api/users' } } } TypeError: Cannot read property 'hrtime' of undefined
    at Object.timeEnd (node_modules\feathers-profiler\lib\index.js:150:38)
    at process._tickCallback (internal/process/next_tick.js:109:7)
01:38:09 api/users::create (rest) 190.5 ms - 0 pending
```

**Comment by eddyystop** [comment]
Fixed in https://github.com/feathersjs/feathers-profiler/pull/7 will be published as v0.1.5.
